#!/bin/sh

# docs: https://git-scm.com/docs/githooks#_pre_commit

echo "Running detekt check..."
OUTPUT="/tmp/detekt-$(date +%s)"
./gradlew detekt > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]
then
    cat "$OUTPUT"
    echo "***********************************************"
    echo "                 Detekt failed                 "
    echo " Please fix the above issues before committing "
    echo "***********************************************"
    rm "$OUTPUT"
    exit $EXIT_CODE
else
    echo "Detekt completed successfully"
fi
rm "$OUTPUT"
